### ISSUE TITLE
Move Issues to EPA Repo

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#159]
After next release shift all issue management and active development to the EPA Repo using https://github.com/google/github-issue-mover.

**Comment by joeponcy** [comment]
Waiting for authorization from USEPA.
Submitted request for authorization to USEPA Github Admin.

**Comment by torrin47** [comment]
Are you still waiting on this one?  I tried using the issue mover tool and was able to move an issue into EPA, but Kris took away my Innovate access, so the tool couldn't clean up/close the old issue. I don't mind moving the issues that way and having you clean up the old ones when I'm done, but it sure would be nice for you to have access to the EPA repo regardless.  Can I help facilitate that?

**Comment by joeponcy** [comment]
I am not sure what's going on now. I assumed that I would still have access to the repo, but it appears that I no longer do.

When I originally tried to use the issue mover tool it let me choose the USEPA repo as the destination but said I needed authorization to complete the request. I just now tried the tool again to see if anything has changed with my permissions, and now the repo doesn't even show up on the list.​

I guess the best solution would be for you to move the issues, and I will clean them up on the Innovate side after you've finished.

**Comment by torrin47** [comment]
I don't mind moving things over, but I would like to resolve the issues with the tool. When you first land on the site, it asks for authorization for your GitHub account - that just fetches the information about what organizations you belong to, and thus what repositories show up in the "Issue to move" list. But even though I'm no longer part of the Innovate organization, I can still add issues one by one to the Issue to Move list by pasting in the complete URL to an issue. After you paste the URL, it shortens the path to just the Organization and repo name as in the screenshot below. I never got any destination repositories to show up automagically, I always had to paste in the full URL there.

![image](https://user-images.githubusercontent.com/2127036/28596027-9bf4e7aa-7164-11e7-9d3d-770f9dc6e5cb.png)

Since the EPA repository is public and anyone with a GitHub account can create and edit issues there, and you still have write access to the EME repository, I'm skeptical that you're actually blocked from migrating issues.

**Comment by torrin47** [comment]
All issues are moved, go ahead and close them here.

**Comment by joeponcy** [comment]
Thanks for the assistance Torrin. 
The tool let me authorize my personal repos and the Innovate repos, but said that I had to request permission to authorize the tool with the EPA repo and presented me with a button to send the request to an EPA admin. 

I did not try pasting the URL into the destination field.

**Comment by joeponcy** [comment]
All outstanding issues transferred to the [USEPA Repo](https://github.com/USEPA/EPA-Metadata-Editor-5) using https://github.com/google/github-issue-mover.
