### ISSUE TITLE
Investigate options for "Set all defaults"

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#28]
Historically the EME had an option for setting all values to defaults, which effectively loaded stuff from a template.  Understanding that we could also allow values to be added from some template XML, how would we help someone author that template and streamline the loading process?

**Comment by dspinosa** [comment]
There are a couple options to consider on this.  Load content (import) from an xml file stored with the EME databases.  Users could edit this as needed.  Maybe make a button on a tool bar to do this, rather than from w/in an edit session on a record.  ...unless we can create a button w/in the editing pages (FillXML() method? ).

**Comment by joeponcy** [comment]
Add this functionalty to the Python Toolbox.
Add Metadata Import/Export tools to EPA Metadata Toolkit Toolbox

**Comment by joeponcy** [comment]
I agree that there's not a whole lot left to set as default. We did discuss a template that the user can customize, but I am not sure what our final decision was on that one.

**Comment by torrin47** [comment]
Ok, just committed toolkit and xslt for saving and merging a template. Definitely want some others to try it and give feedback because what elements to save is pretty subjective.
