### ISSUE TITLE
Create Installer Package with launch conditions

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#68]
- [ ] Create installer UI

- [ ] Check prerequisites and dependencies ( .Net Framework & ArcGIS Version )

- [ ] Install prerequisites

- [ ] Install ArcCatalog components depending on version detected

- [ ] Include option to overwrite or preserve existing EMEdb files if found on system

- [ ] Check to see whether EME 3.2.1 is installed and notifying the user that it should be uninstalled
     - If possible: Include option to uninstall EME 3.2.1 (and removing problematic registry entries)

- [x] Include Python toolbox with EPA update metadata from FGDC script/xslt

The current stand-alone installers preserve existing files by default. This may be the best option as it requires the user to manually delete the db files if they need to be replaced, very unlikely to happen by accident. A flag in the current installer ensures that the files can be overwritten if we release an updated source file.

**Comment by torrin47** [comment]
Couple of questions for ya.  Since we know about synchronization issues involving EME 3.2.1, what is the feasibility of the following?

1. Checking to see whether EME 3.2.1 is installed and notifying the user that it should be uninstalled.
2. Checking to see whether EME 3.2.1 is installed and uninstalling EME 3.2.1 (and removing problematic registry entries)
3. Including Python toolbox with EPA update metadata from FGDC script/xslt.

**Comment by wurlibus** [comment]
1. Is definitely doable
2. May be possible. I will look into it
3. Yes, we can include this as part of the installer package

**Comment by joeponcy** [comment]
1. Is definitely doable May be possible.
2. I will look into it 
3. Yes, we can include this as part of the installer package

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA-Metadata-Editor-5#10

**Comment by joeponcy** [comment]
Issue transferred to the [USEPA Repo](https://github.com/USEPA/EPA-Metadata-Editor-5) using https://github.com/google/github-issue-mover.
