### ISSUE TITLE
Issue-EME 5.0 alpha crashes ArcCatalog

### ISSUE THREAD

**Issue by smjett** [Innovate-Inc/EMEMetadataToolKit#69]
ArcCatalog 10.4.1 crashes with a "serious error" when certain tabs in EME 5.0 are clicked. Generally, these seem to be the "Contact", "Citation", "Points of Contact", etc. tabs. Attached is a zip of a metadata XML file that this is occurring on. This is occurring for myself (jett.steven@epa.gov) as well as another user (harness.catherine@epa.gov).

[ORNL_Education_Download.zip](https://github.com/Innovate-Inc/EMEMetadataToolKit/files/596034/ORNL_Education_Download.zip)

**Comment by joeponcy** [comment]
I believe this happens if the user doesn't have a local contacts file. I had previously assumed this file was created during the Arc installation, but it appears that it is created the first time you save a contact. By default this should be found at ...My Documents\ArcGIS\Descriptions\contacts.xml.

Could you please verify whether or not this fie exists on your machine?

I will work on a new version that addresses this issue.

**Comment by joeponcy** [comment]
This should fix the issue...
Please uninstall any earlier version before running this installer.
[emetoolkit_10.4x_installer-0.9.8.zip](https://github.com/Innovate-Inc/EMEMetadataToolKit/files/596161/emetoolkit_10.4x_installer-0.9.8.zip)

**Comment by joeponcy** [comment]
Need to do some more testing. Ver 0.9.8 does not solve the problem.

**Comment by smjett** [comment]
Thanks. We will grab that new installer and try it out.
